core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home.views import HomeView, PlansView, AchievementsView, VideosView, PhotosView

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('lesson-plans/<int:id>/', PlansView, name='plans'),
    path('achievements/', AchievementsView.as_view(), name='achievements'),
    path('videos/', VideosView.as_view(), name='videos'),
    path('photos/', PhotosView.as_view(), name='photos'),
]

confg/models.py
from django.db import models

# Create your models here.
class Basemodel(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

home/models.py
from django.db import models
from confg.models import Basemodel
# Create your models here.

class Category(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=50, verbose_name='Kategoriya nomi:')

    class Meta:
        ordering = ['-create_at']

    def __str__(self) -> str:
        return self.name
    

class LessonPlans(Basemodel):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='lesson_plan')
    title = models.CharField(max_length=255, verbose_name='Sarlavha')
    photo = models.ImageField(upload_to='dars-ishlanmalar/rasmlar/', verbose_name='Rasm:')
    desc = models.CharField(max_length=255, verbose_name='Qisqacha malumot:')
    file = models.FileField(upload_to='dars-ishlanmalar/', verbose_name='Dars ishlanma:')

    class Meta:
        db_table = 'lesson-plans'
        ordering = ['-create_at']
    
    def __str__(self) -> str:
        return self.title


class Achievements(Basemodel):
    title = models.CharField(max_length=255, verbose_name='sarlavha')
    photo = models.ImageField(upload_to='rasmlar/', verbose_name='Rasm')
    doc = models.FileField(upload_to='documents/', verbose_name='Yutuq')

    class Meta:
        db_table = 'achievements'
        ordering = ['-create_at']
    
    def __str__(self) -> str:
        return self.title
    

class Videos(Basemodel):
    title = models.CharField(max_length=200, verbose_name='Sarlavha')
    video = models.FileField(upload_to='ish_faoliyati/videolar/', verbose_name='Video')

    class Meta:
        db_table = 'videos'
        ordering = ['-create_at']

    def __str__(self) -> str:
        return self.title


class Photos(Basemodel):
    title = models.CharField(max_length=200, verbose_name='Sarlavha')
    photo = models.FileField(upload_to='ish_faoliyati/rasmlar/', verbose_name='Rasm')

    class Meta:
        db_table = 'photos'
        ordering = ['-create_at']

    def __str__(self) -> str:
        return self.title
    

confg/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.views.generic import TemplateView, ListView
from home.models import LessonPlans, Achievements, Videos, Photos, Category
# Create your views here.


class HomeView(TemplateView):
    template_name = 'index.html'

def PlansView(request, id):
    category = Category.objects.get(id=id)
    categories = Category.objects.all()
    plans = LessonPlans.objects.filter(category=category)
    paginator = Paginator(plans, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'plans':page_obj,
        'categories': categories
    } 
    return render(request, 'lesson-plans.html', context)


class AchievementsView(ListView):
    template_name = 'achievements.html'
    model = Achievements
    paginate_by = 3
    context_object_name = 'achievements'


class VideosView(ListView):
    template_name = 'videos.html'
    model = Videos
    paginate_by = 6
    context_object_name = 'videos'


class PhotosView(ListView):
    template_name = 'photos.html'
    model = Photos
    paginate_by = 6
    context_object_name = 'photos'

templates/achievements.html
{% extends 'base.html' %}
{% block content %}
  <section class="services" id="services">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="section-heading">
            <h4>Mening <em>yutuqlarim</em></h4>
          </div>
        </div>
        <div class="col-lg-12">
          <div class="owl-service-item owl-carousel">
            {% for achievement in achievements %}
              {% if achievement.photo %}
                <div class="item">
                  <div class="service-item">
                    <a href="{{ achievement.doc.url }}">
                    <div class="icon">
                      <img src="{{ achievement.photo.url }}" alt="{{ achievement.title }}">
                    </div>
                    </a>
                  </div>
                  <div class="servise-item">
                    {% if achievement.title|length < 100 %}
                      <p>{{ achievement.title }}</p>
                    {% else %}
                      <p>{{ achievement.title|slice:":100" }}...</p>
                    {% endif %}
                  </div>
                </div>
              {% endif %}
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="Rohatov Sherzod" content="">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="icon" href="{% static 'assets/images/logo_remove_backg.png' %}">
    <title>Nargiza Teacher</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-eduwell-style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
    
  </head>

<body>


  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky">
      <div class="container">
          <div class="row">
              <div class="col-12">
                  <nav class="main-nav">
                      <!-- ***** Logo Start ***** -->
                      <a href="{% url 'home:home' %}" class="logo">
                          <img src="{% static 'assets/images/logo_remove_backg.png' %}" alt="EduWell Template" width="188" height="80">
                      </a>
                      <!-- ***** Logo End ***** -->
                      <!-- ***** Menu Start ***** -->
                      <ul class="nav">
                          <li class="scroll-to-section"><a href="{% url 'home:home' %}" class="active">Asosiy</a></li>
                          <li class="scroll-to-section"><a href="{% url 'home:plans' 1 %}">Dars ishlanmalar</a></li>
                          <li class="scroll-to-section"><a href="{% url 'home:achievements' %}">Yutuqlar</a></li>
                          <li class="has-sub">
                              <a href="javascript:void(0)">Ish Faoliyati</a>
                              <ul class="sub-menu">
                                  <li><a href="https://www.youtube.com/@NargizaTeacherr">Videolar</a></li>
                                  <li><a href="{% url 'home:photos' %}">Rasmlar</a></li>
                              </ul>
                          </li>
                      </ul>        
                      <a class='menu-trigger'>
                          <span>Menu</span>
                      </a>
                      <!-- ***** Menu End ***** -->
                  </nav>
              </div>
          </div>
      </div>
  </header>
  <!-- ***** Header Area End ***** -->


  {% block  content %}

  {% endblock content %}

  <section class="contact-us" id="contact-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <ul class="social-icons">
            <li><a href="https://www.instagram.com/nargiza_teacher_"><img src="{% static 'assets/images/instagram.png' %}" alt=""></a></li>
            <li><a href="https://t.me/nargiza_teacher"><img src="{% static 'assets/images/telegram.png' %}" alt=""></a></li>
            <li><a href="#"><img src="{% static 'assets/images/facebook.png' %}" alt=""></a></li>
            <li><a href="https://youtube.com/@nargiza_teacher?si=cABu29sumK9pnmHu"><img src="{% static 'assets/images/you_tube.png' %}" alt=""></a></li>
          </ul>
        </div>
        <div class="col-lg-12">
          <p class="copyright">Created by © Rokhatov Sherzod for Nargiza Shermatova. 
          
          <br>For reference: <a rel="sponsored" href="https://t.me/Rohatov2" target="_blank">Telegram</a></p>
        </div>
      </div>
    </div>
  </section>

  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <!-- <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script> -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="{% static 'assets/js/isotope.min.js' %}"></script>
  <script src="{% static 'assets/js/owl-carousel.js' %}"></script>
  <script src="{% static 'assets/js/lightbox.js' %}"></script>
  <script src="{% static 'assets/js/tabs.js' %}"></script>
  <script src="{% static 'assets/js/video.js' %}"></script>
  <script src="{% static 'assets/js/slick-slider.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- ***** Main Banner Area Start ***** -->
  <section class="main-banner" id="top">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 align-self-center">
          <div class="header-text">
            <h1>SHERMATOVA NARGIZA AYNAQULOVNA</h1>
            <h2>Bo'ka tumani 4-sonli maktabning boshlang'ich sinf o'qituvchisi Shermatova Nargizaning shaxsiy <em>BLOGI</em></h2>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="right-image">
            <img src="{% static 'assets/images/banner-right-image.png' %}" alt="">
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- ***** Main Banner Area End ***** -->
{% endblock content %}

templates/lesson-plans.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="lesson" id="lesson">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="section-heading">
          <h4>Mening <em>dars ishlanmalarim</em></h4>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="category-menu">
          {% for cat in categories %}
            <a href="{% url 'home:plans' cat.id %}" class="category-item" id="nav-{{ cat.name }}-tab" data-toggle="tab" href="#nav-{{ cat.name }}" role="tab" aria-controls="nav-{{ cat.name }}" aria-selected="false">{{ cat.name }} </a>
          {% endfor %}
        </div>
        <div class="owl-service-item owl-carousel">
        {% for plan in plans %}
          <div class="item">
            <div class="service-item">
              <a href="{{ plan.file.url }}">
              <img src="{{ plan.photo.url }}" class="card-img-top" alt="{{ plan.title }}">
              <div class="card-body">
                <h5 class="card-title">{{ plan.title }}</h5>
                <p class="card-text">{{ plan.desc }}</p>
              </a>
            </div>
          </div>
          </div>
        {% endfor %}
      </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/photos.html
{% extends 'base.html' %}
{% block content %}
    <section class="testimonials" id="testimonials">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="section-heading">
                <h4>Dars jarayonidan <em>fotolavhalar</em></h4>
              </div>
            </div>
              <div class="col-lg-12">
                <div class="owl-testimonials owl-carousel testimonials" style="position: relative; z-index: 5;">
                  {% for photo in photos %}
                  <div class="item">
                    {% if photo.photo %}
                      <div class="image-container">
                        <img src="{{ photo.photo.url }}" alt="">
                      </div>
                    {% endif %}
                    <div class="title-container">
                      <h4>Catherine Walk</h4>
                      <p>“Just think about TemplateMo if you need free CSS templates for your website”</p>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              </div>            
          </div>
        </div>
      </section>
{% endblock content %}

templates/videos.html
{% extends 'base.html' %}
{% block content %}
    <section class="videos" id="testimonials">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="section-heading">
                <h4>Dars jarayonidan <em>videolavhalar</em></h4>
              </div>
            </div>
            <div class="col-lg-12">
              <div class="owl-testimonials owl-carousel" style="position: relative; z-index: 5;">
                {% for video in videos %}
                  <div class="item">
                    {% if video.video %}
                      <video class="carousel-video" controls="controls">
                        <source src="{{ video.video.url }}" type="video/mp4">
                      </video>
                    {% endif %}
                    <div class="video-title">
                      <h4>{{ video.title }}</h4>
                    </div>
                  </div>
                {% endfor %}
              </div>
            </div>            
          </div>
        </div>
      </section>
{% endblock content %}